# Generated by Django 4.2.5 on 2023-09-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Category name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Category description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('sending_time', models.TimeField(auto_now_add=True, verbose_name='время отправки рассылок')),
                ('frequency', models.CharField(choices=[('DAILY', 'Ежедневно'), ('WEEKLY', 'Раз в неделю'), ('MONTHLY', 'Раз в месяц')], max_length=50, verbose_name='частота отправки')),
                ('status', models.CharField(choices=[('FINISH', 'Завершена'), ('CREATE', 'Создана'), ('START', 'Запущена')], max_length=50, verbose_name='статус')),
                ('finish_date', models.DateField(default='2025-01-01', verbose_name='дата прекращения рассылки')),
                ('finish_time', models.TimeField(default='00:00', verbose_name='время прекращения рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('sending_time',),
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(auto_now_add=True, verbose_name='Время последней отправки')),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], default='ok', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Лог отправки',
                'verbose_name_plural': 'Логи отправок',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Topic')),
                ('message', models.TextField(verbose_name='Message body')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.category')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='MessageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveSmallIntegerField(verbose_name='version number')),
                ('version_name', models.CharField(max_length=100, verbose_name='version name')),
                ('is_active', models.BooleanField(verbose_name='flag of the current version')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='message')),
            ],
        ),
    ]
