# Generated by Django 4.2.5 on 2023-09-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Ежедневно'), ('WEEKLY', 'Раз в неделю'), ('MONTHLY', 'Раз в месяц')], default='daily', max_length=50, verbose_name='частота отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('FINISH', 'Завершена'), ('CREATE', 'Создана'), ('START', 'Запущена')], default='created', max_length=50, verbose_name='статус'),
        ),
    ]
