# Generated by Django 4.2.5 on 2023-09-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('id',), 'verbose_name': 'Mailing', 'verbose_name_plural': 'Mailings'},
        ),
    ]
