# Generated by Django 4.2.5 on 2023-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('preview_pic', models.ImageField(blank=True, null=True, upload_to='blog_pictures/', verbose_name='Picture')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
